commercetools/commercetools-api-reference

.gitignore
.travis.yml
README.md
bin/explode-raml.js
bin/validate-sources.js
json-schema-draft4.json
package.json

Hi everybody, as the TravisCI integration is working now and the first validation results showed that they are actual bugs let's merge this so the Travis builds have a meaning (currently it assumes ruby ;-)

TravisCI; RAML, schema and example validation

---

types/cart-discount/CartDiscountChangeCartPredicateAction.raml
types/cart-discount/CartDiscountChangeIsActiveAction.raml
types/cart-discount/CartDiscountChangeNameAction.raml
types/cart-discount/CartDiscountChangeRequiresDiscountCodeAction.raml
types/cart-discount/CartDiscountChangeSortOrderAction.raml
types/cart-discount/CartDiscountChangeStackingModeAction.raml
types/cart-discount/CartDiscountChangeTargetAction.raml
types/cart-discount/CartDiscountChangeValueAction.raml
types/cart-discount/CartDiscountSetCustomFieldAction.raml
types/cart-discount/CartDiscountSetCustomTypeAction.raml
types/cart-discount/CartDiscountSetDescriptionAction.raml
types/cart-discount/CartDiscountSetValidFromAction.raml
types/cart-discount/CartDiscountSetValidUntilAction.raml

This PR:
- adds missing updateActions to cartDiscount endpoint https://github.com/commercetools/commercetools-api-reference/commit/95cb6209baeab7f30e581d6c3ffcf6b360e1a142
- adds examples to all updateActions of the cartDiscount endpoint https://github.com/commercetools/commercetools-api-reference/commit/3c690c82e699fe73df6fb3d2ea0cb813da40c496

CartDiscount examples

---

README.md

This PR adds basic instructions on how to generate postman collection to Readme.

Add instructions on generating postman collection

---

examples/Cart/CartAddItemShippingAddressAction.json
examples/Cart/CartApplyDeltaToCustomLineItemShippingDetailsTargetsAction.json
examples/Cart/CartApplyDeltaToLineItemShippingDetailsTargetsAction.json
examples/Cart/CartChangeCustomLineItemQuantityAction.json
examples/Cart/CartRemoveItemShippingAddressAction.json
examples/Cart/CartSetAnonymousIdAction.json
examples/Cart/CartSetCustomLineItemCustomTypeAction.json
examples/Cart/CartSetCustomLineItemShippingDetailsAction.json
examples/Cart/CartSetCustomLineItemTaxAmountAction.json
examples/Cart/CartSetCustomLineItemTaxRateAction.json
examples/Cart/CartSetCustomerGroupAction.json
examples/Cart/CartSetLineItemPriceAction.json
examples/Cart/CartSetLineItemShippingDetailsAction.json
examples/Cart/CartUpdateItemShippingAddressAction.json
types/cart/updates/CartAddItemShippingAddressAction.raml
types/cart/updates/CartApplyDeltaToCustomLineItemShippingDetailsTargetsAction.raml
types/cart/updates/CartApplyDeltaToLineItemShippingDetailsTargetsAction.raml
types/cart/updates/CartChangeCustomLineItemQuantityAction.raml
types/cart/updates/CartRemoveItemShippingAddressAction.raml
types/cart/updates/CartSetAnonymousIdAction.raml
types/cart/updates/CartSetCustomLineItemCustomTypeAction.raml
types/cart/updates/CartSetCustomLineItemShippingDetailsAction.raml
types/cart/updates/CartSetCustomLineItemTaxAmountAction.raml
types/cart/updates/CartSetCustomLineItemTaxRateAction.raml
types/cart/updates/CartSetCustomerGroupAction.raml
types/cart/updates/CartSetLineItemPriceAction.raml
types/cart/updates/CartSetLineItemShippingDetailsAction.raml
types/cart/updates/CartUpdateItemShippingAddressAction.raml

I added missing Actions. Please let me know, if now all are covered. Thanks

Added missing examples to the TaxCategory RAML update Action Files for CART

---

types/error/DiscountCodeNonApplicableError.raml
types/error/DuplicateFieldError.raml
types/error/DuplicateFieldWithConflictingResourceError.raml
types/error/EnumValueIsUsedError.raml
types/error/ExtensionBadResponseError.raml
types/error/ExtensionNoResponseError.raml
types/error/ExtensionUpdateActionsFailedError.raml
types/error/MatchingPriceNotFoundError.raml
types/error/MissingTaxRateForCountryError.raml
types/types.raml

add error codes

---

types/error/ErrorByExtension.raml
types/error/ExtensionBadResponseError.raml
types/error/ExtensionNoResponseError.raml
types/error/ExtensionUpdateActionsFailedError.raml
types/types.raml

https://github.com/commercetools/docs.commercetools.com/pull/1270

fix ExtensionErrorResponse object

---

types/PagedQueryResponse.raml
types/Update.raml
types/UpdateAction.raml

**Summary**
This PR adds generator annotations missing on some of our `common` data types.

Add missing package annotations.

---

resources/cart-discounts.raml
types/cart-discount/CartDiscount.raml
types/cart-discount/CartDiscountDraft.raml
types/cart-discount/updates/CartDiscountSetKeyAction.raml
types/types.raml
update-actions.raml

https://github.com/commercetools/docs.commercetools.com/pull/1297

supoprt key in CartDiscount

---

types/state/StateRoleEnum.raml

See https://github.com/labd/commercetools-go-sdk/issues/44

Add missing StateRole.Enum definition

---

types/error/InvalidJsonInputError.raml

Reverts commercetools/commercetools-api-reference#112

Revert "Add missing detailedErrorMessage on InvalidJsonInputError"

---

securitySchemes/oauth2.raml
securitySchemes/oauth2_anonymous.raml
securitySchemes/oauth2_password.raml
securitySchemes/oauth2_refresh.raml
traits/errorable.raml
types/cart-discount/CartDiscountDraft.raml
types/category/CategoryDraft.raml
types/discount-code/DiscountCodeDraft.raml
types/me/MyPayment.raml
types/me/MyPaymentDraft.raml
types/me/MyTransactionDraft.raml
types/product-discount/ProductDiscount.raml
types/product-discount/ProductDiscountDraft.raml
types/product/ProductDraft.raml
types/project/Project.raml
types/review/Review.raml
types/review/ReviewDraft.raml
types/shopping-list/ShoppingList.raml
types/shopping-list/ShoppingListDraft.raml

Just small issues I found in the doc.

Fixing few small issues with the documentation

---

examples/ShippingMethod/ShippingMethodSetLocalizedDescriptionAction.json
types/shipping-method/ShippingMethod.raml
types/shipping-method/ShippingMethodDraft.raml
types/shipping-method/updates/ShippingMethodSetLocalizedDescriptionAction.raml
types/types.raml

https://github.com/commercetools/commercetools-php-sdk/issues/545

add localized description to shippingMethods

---

examples/Customer/CustomerAddStoreAction.json
examples/Customer/CustomerRemoveStoreAction.json
examples/Customer/CustomerSetStoresAction.json
examples/Order/OrderSetStoreAction.json
types/message/OrderStoreSetMessage.raml
types/order/updates/OrderSetStoreAction.raml
types/types.raml

https://github.com/commercetools/commercetools-php-sdk/issues/544

add setStore action and message

---

resources/in-store.raml
resources/shipping-methods.raml

added some scopes missing for the merging with the other PR 
but I think that something is missing:
in https://github.com/commercetools/docs.commercetools.com/pull/1437/files
Missing scope for other endpoints like
/matching-orderedit:
/matching-location:

add scope for matching cart endpoint

---

resources/me.raml
types/me/MyShoppingListDraft.raml

Closes https://github.com/commercetools/commercetools-php-sdk/issues/573

Support my shoppinglist

---

api.swagger.json
api.swagger3.json
postman/gen.properties
resources/me.raml

According to the documentation this endpoint doesn't exist, neither does the corresponding update actions

Remove the MyOrderCreate endpoint 

---

.github/workflows/update.yml
Makefile
api.swagger.json
api.swagger3.json
examples/Store/StoreAddSupplyChannelAction.json
examples/Store/StoreRemoveSupplyChannelAction.json
examples/Store/StoreSetSupplyChannelsAction.json
types/store/Store.raml
types/store/StoreDraft.raml
types/store/updates/StoresAddSupplyChannelsAction.raml
types/store/updates/StoresRemoveSupplyChannelsAction.raml
types/store/updates/StoresSetSupplyChannelsAction.raml
types/types.raml

Add support for store based inventory filtering:
https://github.com/commercetools/docs.commercetools.com/pull/1602

Add support for store based inventory filtering

---

api.swagger.json
api.swagger3.json
types/cart/LineItem.raml
types/cart/LineItemDraft.raml
types/me/MyLineItemDraft.raml
types/me/updates/MyCartAddLineItemAction.raml
types/order-edit/updates/StagedOrderAddLineItemAction.raml

Closes https://github.com/commercetools/commercetools-api-reference/issues/166

Support addedAt to cart LineItem

---

api.swagger.json
api.swagger3.json
types/error/ReferencedResourceNotFoundError.raml

add ReferencedResourceNotFoundError

---

.github/workflows/update.yml
api.swagger.json
api.swagger3.json
examples/Cart/CartSetLineItemDistributionChannelAction.json
examples/OrderEdit/StagedOrderSetLineItemDistributionChannelAction.json
types/cart/updates/CartSetLineItemDistributionChannelAction.raml
types/me/updates/MyCartSetLineItemDistributionChannelAction.raml
types/order-edit/updates/StagedOrderSetLineItemDistributionChannelAction.raml
types/types.raml

add SetLineItemDistributionChannel actions

---

api.swagger.json
api.swagger3.json
resources/states.raml
update-actions.raml

Adding Support to get State By Key to solve this issue:
https://github.com/commercetools/commercetools-sdk-typescript/issues/31

Adding Support to get State By Key

---

.github/workflows/sdk.yml

Adding Csharp Auto Generate SDK Job

Csharp Auto Generated SDK Job

---

api-specs/api/examples/ShippingMethod/ShippingMethodSetCustomFieldAction.json
api-specs/api/examples/ShippingMethod/ShippingMethodSetCustomTypeAction.json
api-specs/api/types/shipping-method/ShippingMethod.raml
api-specs/api/types/shipping-method/ShippingMethodDraft.raml
api-specs/api/types/shipping-method/updates/ShippingMethodSetCustomFieldAction.raml
api-specs/api/types/shipping-method/updates/ShippingMethodSetCustomTypeAction.raml
api-specs/api/types/type/ResourceTypeId.raml
api-specs/api/types/types.raml

Add custom fields to shipping method

---

api-specs/importapi/api.raml
api-specs/importapi/examples/category-import-response.json
api-specs/importapi/examples/customer-import-response.json
api-specs/importapi/examples/import-operation-paged.response.json
api-specs/importapi/examples/import-operation-validation-failed.json
api-specs/importapi/examples/import-operation-with-unresolved-references.json
api-specs/importapi/examples/inventory-import-response.json
api-specs/importapi/types/category-import.raml
api-specs/importapi/types/common.raml
api-specs/importapi/types/customer-import.raml
api-specs/importapi/types/import-operation.raml
api-specs/importapi/types/import-summary.raml
api-specs/importapi/types/order-import.raml
api-specs/importapi/types/order-patch-import.raml
api-specs/importapi/types/price-import.raml
api-specs/importapi/types/product-draft-import.raml
api-specs/importapi/types/product-import.raml
api-specs/importapi/types/product-variant-import.raml
oas/openapi.yaml

update import-api SDK before release changes to doc repo 
cc: @ashishhk

import-api camelCase and restructure processing states

---

.github/workflows/sdk-postman.yml

feat: add generate connect postman collection to sdk-postman workflow
cc: @prateek-ct

feat: add generate connect postman collection to sdk-postman workflow
